# Generated by Django 2.1.3 on 2018-11-24 13:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_order_dt'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 11, 24, 13, 20, 2, 373334, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
